[keybindings]
"Tab"       =   "move right 1"
"Shift+Tab" =   "move left 1"
"Space"     =   "playpause"
"H"         =   "seek -10000"
"L"         =   "seek +10000"
"q"         =   "back"
"Q"         =   "quit"
"Ctrl+d"    =   "move down 10"
"Ctrl+u"    =   "move up 10"
"g"         =   "move top"
"G"         =   "move bottom"
"s"         =   "shuffle"

[theme]
background          =   "#1d2021"
primary             =   "#ebdbb2"
secondary           =   "#8a9984"
title               =   "#98791a"
playing             =   "#1d2021"
playing_selected    =   "#8ec07c"
playing_bg          =   "#8ec07c"
highlight           =   "#ebdbb2"
highlight_bg        =   "#3c3836"
error               =   "#ebdbb2"
error_bg            =   "#fb4934"
statusbar           =   "#282828"
statusbar_progress  =   "#8ec07c"
statusbar_bg        =   "#8ec97c"
cmdline             =   "#ebdbb2"
cmdline_bg          =   "#282828"
