#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
export SSH_AUTH_SOCK

# touch screen only LVDS1
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Pen stylus") LVDS1
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Pen eraser") LVDS1
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Finger touch") LVDS1

eval $(ssh-agent)
exec bluetooth off &

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

export SSH_ASKPASS=/usr/lib/ssh/ssh-askpass
exec i3
#exec gnome-session
