#!/bin/bash
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

eval $(ssh-agent)
exec bluetooth off &

export SSH_ASKPASS=/usr/lib/ssh/ssh-askpass
exec i3
