# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Use colors?
use_color=true

# sources the host specific bashrc
ostmp=`uname -a`

if [[ ${ostmp} == *"Linux"* ]] ; then
    source /home/${USER}/Repositories/github.com/hringriin/dotfiles/repo/bash/bashrc.d/linux/general
else
    source /Users/${USER}/Repositories/github.com/hringriin/dotfiles/repo/bash/bashrc.d/macos/general
fi

# Try to keep environment pollution down, EPA loves us.
unset use_color ostmp

# Commented out, don't overwrite xterm -T "title" -n "icontitle" by default.
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    ;;
*)
    ;;
esac

# enable bash completion in interactive shells
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# if the command-not-found package is installed, use it
if [ -x /usr/lib/command-not-found ]; then
    function command_not_found_handle {
            # check because c-n-f could've been removed in the meantime
                if [ -x /usr/lib/command-not-found ]; then
           /usr/bin/python /usr/lib/command-not-found -- $1
                   return $?
        else
           return 127
        fi
    }
fi

# Bash History
HISTCONTROL=ignoredups:erasedups    # no duplicate entries
HISTSIZE=99999                      # big big history
HISTFILESIZE=99999                  # big big history
shopt -s histappend                 # append to history, do not overwrite it

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
